variable "repository_name" {}
variable "object_name" {}
variable "bucket_name" {}
variable "version_id" {}
variable "project" {}
variable "service" {}
variable "runtime" {}
variable "shell" {}
variable "port" {}
variable "db_pwd" {}
variable "instance_class" {}
variable "delete_service_on_destroy" {}
variable "service_account" {}